project_id = "txmafyswuzslwlixszmf"

[functions.mtn-momo-balance]
verify_jwt = true

[functions.mtn-momo-callback]
verify_jwt = true

[functions.mtn-momo-invoice]
verify_jwt = true

[functions.mtn-momo-create-invoice]
verify_jwt = true

[functions.mtn-momo-invoice-status]
verify_jwt = true

[functions.mtn-momo-cancel-invoice]
verify_jwt = true

[functions.debug-logger]
verify_jwt = true